//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLeadObjects.Resources.Orders
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Orders
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Orders()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMLeadObjects.Resources.Orders.Orders", typeof(Orders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Agregar
        {
            get
            {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Nueva Orden.
        /// </summary>
        public static string AgregarNuevaOrden
        {
            get
            {
                return ResourceManager.GetString("AgregarNuevaOrden", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Orden.
        /// </summary>
        public static string AgregarOrden
        {
            get
            {
                return ResourceManager.GetString("AgregarOrden", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar
        {
            get
            {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar
        {
            get
            {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string Cliente
        {
            get
            {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios.
        /// </summary>
        public static string Comentarios
        {
            get
            {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string de
        {
            get
            {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string Descargar
        {
            get
            {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Fecha
        {
            get
            {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        public static string Filtrar
        {
            get
            {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Intcomex o numero de orden del cliente ,SKU, numero de parte, marca, descripcion.
        /// </summary>
        public static string FulltextSearch
        {
            get
            {
                return ResourceManager.GetString("FulltextSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros para los filtros seleccionados.
        /// </summary>
        public static string NoRegistros
        {
            get
            {
                return ResourceManager.GetString("NoRegistros", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Escriba las ordenes separadas por &quot;,&quot;.
        /// </summary>
        public static string NotaFiltrarOrdenes
        {
            get
            {
                return ResourceManager.GetString("NotaFiltrarOrdenes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ordenes.
        /// </summary>
        public static string Ordenes
        {
            get
            {
                return ResourceManager.GetString("Ordenes", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string Order
        {
            get
            {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Orden del Cliente.
        /// </summary>
        public static string OrderCustomer
        {
            get
            {
                return ResourceManager.GetString("OrderCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Precio Extendido.
        /// </summary>
        public static string PrecioExtendido
        {
            get
            {
                return ResourceManager.GetString("PrecioExtendido", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Precio Unitario.
        /// </summary>
        public static string PrecioUnitario
        {
            get
            {
                return ResourceManager.GetString("PrecioUnitario", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a producto.
        /// </summary>
        public static string product
        {
            get
            {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        public static string Producto
        {
            get
            {
                return ResourceManager.GetString("Producto", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string Qty
        {
            get
            {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Realizada el.
        /// </summary>
        public static string RealizadaEn
        {
            get
            {
                return ResourceManager.GetString("RealizadaEn", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string Regresar
        {
            get
            {
                return ResourceManager.GetString("Regresar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        public static string Resultados
        {
            get
            {
                return ResourceManager.GetString("Resultados", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Selecionar estado.
        /// </summary>
        public static string SelectStatus
        {
            get
            {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Todas las paginas.
        /// </summary>
        public static string TodasLasPaginas
        {
            get
            {
                return ResourceManager.GetString("TodasLasPaginas", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Unidad.
        /// </summary>
        public static string Unidad
        {
            get
            {
                return ResourceManager.GetString("Unidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ver detalle.
        /// </summary>
        public static string VerDetalle
        {
            get
            {
                return ResourceManager.GetString("VerDetalle", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ver log.
        /// </summary>
        public static string VerLog
        {
            get
            {
                return ResourceManager.GetString("VerLog", resourceCulture);
            }
        }
    }
}
