//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLeadObjects.Resources.News {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class News {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal News() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMLeadObjects.Resources.News.News", typeof(News).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar.
        /// </summary>
        public static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticia actualizada con exito.
        /// </summary>
        public static string ActualizacionExitosa {
            get {
                return ResourceManager.GetString("ActualizacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al actualizar la noticia.
        /// </summary>
        public static string ActualizacionFallida {
            get {
                return ResourceManager.GetString("ActualizacionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar noticia.
        /// </summary>
        public static string AgregarNoticia {
            get {
                return ResourceManager.GetString("AgregarNoticia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticia creada con exito.
        /// </summary>
        public static string CreacionExitosa {
            get {
                return ResourceManager.GetString("CreacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al crear la noticia.
        /// </summary>
        public static string CreacionFallida {
            get {
                return ResourceManager.GetString("CreacionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar noticia.
        /// </summary>
        public static string EditarNoticia {
            get {
                return ResourceManager.GetString("EditarNoticia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error obteniendo las noticias.
        /// </summary>
        public static string ErrorObteniendoNoticias {
            get {
                return ResourceManager.GetString("ErrorObteniendoNoticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es-CO.
        /// </summary>
        public static string Localizacion {
            get {
                return ResourceManager.GetString("Localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticias.
        /// </summary>
        public static string Noticias {
            get {
                return ResourceManager.GetString("Noticias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva noticia.
        /// </summary>
        public static string NuevaNotica {
            get {
                return ResourceManager.GetString("NuevaNotica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo noticia es requerido.
        /// </summary>
        public static string RequiredDesc {
            get {
                return ResourceManager.GetString("RequiredDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo titulo noticia es requerido.
        /// </summary>
        public static string RequiredTitulo {
            get {
                return ResourceManager.GetString("RequiredTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo noticia.
        /// </summary>
        public static string TituloNoticia {
            get {
                return ResourceManager.GetString("TituloNoticia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ver más.
        /// </summary>
        public static string VerMas {
            get {
                return ResourceManager.GetString("VerMas", resourceCulture);
            }
        }
    }
}
