//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLeadObjects.Resources.Tokens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TokenStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMLeadObjects.Resources.Tokens.TokenStatus", typeof(TokenStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de activación.
        /// </summary>
        public static string ActivationDate {
            get {
                return ResourceManager.GetString("ActivationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Negra.
        /// </summary>
        public static string Blacklisted {
            get {
                return ResourceManager.GetString("Blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar estado.
        /// </summary>
        public static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devuelta.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del estado.
        /// </summary>
        public static string DescriptionStatus {
            get {
                return ResourceManager.GetString("DescriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de expiración.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token no procesado.
        /// </summary>
        public static string FailToken {
            get {
                return ResourceManager.GetString("FailToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar estado de tokens.
        /// </summary>
        public static string GetToken {
            get {
                return ResourceManager.GetString("GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave del producto.
        /// </summary>
        public static string ProductKey {
            get {
                return ResourceManager.GetString("ProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canjeado.
        /// </summary>
        public static string Redeemed {
            get {
                return ResourceManager.GetString("Redeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es requerido y sin espacios en blanco.
        /// </summary>
        public static string TokenIsRequired {
            get {
                return ResourceManager.GetString("TokenIsRequired", resourceCulture);
            }
        }
    }
}
