//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMLeadObjects.Resources.CommonMistakes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMistakes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMistakes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMLeadObjects.Resources.CommonMistakes.CommonMistakes", typeof(CommonMistakes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Acept {
            get {
                return ResourceManager.GetString("Acept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesable.
        /// </summary>
        public static string Actionable {
            get {
                return ResourceManager.GetString("Actionable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea eliminar este registro?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el registro.
        /// </summary>
        public static string CreateError {
            get {
                return ResourceManager.GetString("CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro creado con éxito.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el registro.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro eliminado con éxito.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CódigoError.
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error obteniendo los errores comunes.
        /// </summary>
        public static string ErrorGetCommonMistakes {
            get {
                return ResourceManager.GetString("ErrorGetCommonMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe el código de error.
        /// </summary>
        public static string ExistCommonMistake {
            get {
                return ResourceManager.GetString("ExistCommonMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HTTPErrorRespuesta.
        /// </summary>
        public static string HttpErrorResponse {
            get {
                return ResourceManager.GetString("HttpErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MensajeError.
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MensajeURL.
        /// </summary>
        public static string MessageURL {
            get {
                return ResourceManager.GetString("MessageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MismaURL.
        /// </summary>
        public static string MismaURL {
            get {
                return ResourceManager.GetString("MismaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros.
        /// </summary>
        public static string NoFoundRecords {
            get {
                return ResourceManager.GetString("NoFoundRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a resultados.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesable es un campo obligatorio.
        /// </summary>
        public static string RequiredActionable {
            get {
                return ResourceManager.GetString("RequiredActionable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ErrorCode es un campo numérico positivo obligatorio.
        /// </summary>
        public static string RequiredErrorCode {
            get {
                return ResourceManager.GetString("RequiredErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ErrorRespuesta es un campo obligatorio.
        /// </summary>
        public static string RequiredHttpErrorResponse {
            get {
                return ResourceManager.GetString("RequiredHttpErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MensajeError es un campo obligatorio.
        /// </summary>
        public static string RequiredMessageError {
            get {
                return ResourceManager.GetString("RequiredMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errores comunes.
        /// </summary>
        public static string TitleView {
            get {
                return ResourceManager.GetString("TitleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el registro.
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro actualizado con éxito.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
